#!/bin/bash

for item in ~/"Library/Developer/Xcode/Templates/Apple ][" ~/"Library/Developer/Xcode/Templates/File Templates/Apple ]["
do
    if [ -d "$item" ]
    then
        rm -rf "$item"
    fi
done
